# -*- coding: utf-8 -*-
"""case study 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChSByNAD9zP1Liq3lWL_mHPXdLDX1VqU
"""

part-A python programming

import pandas as pd
student_ids = [f"S{i}" for i in range(1, 11)]

study_hours      = [2, 3, 4, 5, 6, 7, 8, 4, 6, 9]
attendance_pct   = [65, 70, 75, 80, 85, 90, 92, 78, 88, 95]
assignment_marks = [55, 60, 65, 72, 78, 85, 88, 70, 80, 92]
prior_marks      = [58, 62, 68, 70, 76, 82, 86, 72, 79, 90]
final_marks      = [60, 64, 70, 75, 82, 88, 91, 74, 84, 94]

students_df = pd.DataFrame({
    "Student": student_ids,
    "Study_Hours": study_hours,
    "Attendance": attendance_pct,
    "Assignment_Score": assignment_marks,
    "Previous_Score": prior_marks,
    "Final_Score": final_marks,
})

def show_section(title, content):
    print(f"\n=== {title} ===")
    print(content)

print(f"Total students in dataset: {students_df.shape[0]}")

show_section("Columns", list(students_df.columns))
show_section("Data Types", students_df.dtypes)
show_section("First 5 Rows", students_df.head(5))
show_section("Last 5 Rows", students_df.tail(5))

"""Part B – Pandas Data Analysis

7.8. Create and display the complete DataFrame
"""

print("\nComplete Dataset:")
print(students_df.to_string())

"""9. Calculate Average"""

numeric_columns = ["Study_Hours", "Attendance", "Assignment_Score",
                   "Previous_Score", "Final_Score"]

column_averages = students_df[numeric_columns].mean()

print("\nAverage Values:")
print(column_averages)

"""10. Student with Highest Final Score"""

top_row_index = students_df["Final_Score"].idxmax()
top_student = students_df.loc[top_row_index]

print("\nStudent with Highest Final Score:")
print(top_student)

"""11. Student with Lowest Final Score"""

bottom_row_index = students_df["Final_Score"].idxmin()
bottom_student = students_df.loc[bottom_row_index]

print("\nStudent with Lowest Final Score:")
print(bottom_student)

"""12. Students with Attendance Greater Than 80%"""

high_attendance = students_df[students_df["Attendance"] > 80]

print("\nStudents with Attendance Above 80:")
print(high_attendance)

"""13. Students with Final Score Greater Than 80"""

high_scorers = students_df[students_df["Final_Score"] > 80]

print("\nStudents with Final Score Above 80:")
print(high_scorers)

"""14. Statistical Summary"""

summary_stats = students_df.describe()

print("\nSummary Statistics:")
print(summary_stats)

"""Part C – NumPy Numerical Analysis"""

import numpy as np

final_array = students_df["Final_Score"].to_numpy()

print("\nFinal Scores:", final_array)
print("Mean:", np.mean(final_array))
print("Median:", np.median(final_array))
print("Maximum:", np.max(final_array))
print("Minimum:", np.min(final_array))
print("Standard Deviation:", np.std(final_array))

"""Part D – Data Visualization

Study Hours vs Final Score:
"""

import matplotlib.pyplot as plt

hours_studied = students_df["Study_Hours"]
exam_results = students_df["Final_Score"]

plt.figure(figsize=(7, 5))
plt.scatter(hours_studied, exam_results)
plt.xlabel("Study Hours")
plt.ylabel("Final Score")
plt.title("Study Hours vs Final Score")
plt.show()

"""Attendance vs Final Score:"""

attendance_values = students_df["Attendance"]
exam_results = students_df["Final_Score"]

plt.figure(figsize=(7, 5))
plt.scatter(attendance_values, exam_results)
plt.xlabel("Attendance (%)")
plt.ylabel("Final Score")
plt.title("Attendance vs Final Score")
plt.show()

"""Distribution of Final Scores:"""

plt.figure(figsize=(7, 5))
plt.hist(students_df["Final_Score"], bins=5, edgecolor="black")
plt.xlabel("Final Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Final Scores")
plt.show()

"""Student-wise Final Scores:"""

plt.figure(figsize=(8, 5))
plt.bar(students_df["Student"], students_df["Final_Score"])
plt.xlabel("Student")
plt.ylabel("Final Score")
plt.title("Student-wise Final Scores")
plt.show()

"""8. Part E – Linear Algebra

15. Create matrix X using NumPy.
"""

feature_columns = ["Study_Hours", "Attendance", "Assignment_Score"]

feature_matrix = students_df[feature_columns].values

print("\nMatrix X:")
print(feature_matrix)

"""16.Find the shape of X"""

print("Shape:", feature_matrix.shape)

"""Calculate the transpose XT"""

print("\nTranspose of X:")
print(feature_matrix.T)

"""Calculate the dot product between Study Hours and Final Score."""

hours_array = students_df["Study_Hours"].values
scores_array = students_df["Final_Score"].values

hours_scores_dot = np.dot(hours_array, scores_array)

print("\nDot Product:", hours_scores_dot)

"""9. Part F – Calculus: Differentiation"""

def score_model(hours):
    return 40 + 5 * hours - 0.2 * hours ** 2


def score_slope(hours):
    return 5 - 0.4 * hours


for hours in range(1, 11):
    print(hours, score_model(hours), score_slope(hours))

"""10. Part G – Calculus: Integration"""

def learning_gain(hours):
    return 5 * hours - 0.2 * hours ** 2


hours_grid = np.linspace(0, 5, 1000)
gain_values = learning_gain(hours_grid)

approx_area = np.trapezoid(gain_values, hours_grid)

print("Numerical Area:", approx_area)

"""Part H – Correlation Analysis"""

correlation_matrix = students_df.corr(numeric_only=True)

print("\nCorrelation Matrix:")
print(correlation_matrix)

"""Correlation Heatmap"""

import seaborn as sns

plt.figure(figsize=(8, 6))
sns.heatmap(
    students_df.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
)
plt.title("Correlation Heatmap")
plt.show()

"""Part I – Mini Prediction Model Using Linear Algebra"""

feature_names = ["Study_Hours", "Attendance", "Assignment_Score"]

predictors = students_df[feature_names].values
target = students_df["Final_Score"].values

design_matrix = np.column_stack((np.ones(len(predictors)), predictors))

coefficients = np.linalg.inv(design_matrix.T @ design_matrix) @ design_matrix.T @ target

print("\nCoefficients:")
print(coefficients)

"""13. Part J – Final Interpretation

What is the average final score?
"""

mean_final_score = students_df["Final_Score"].mean()

print("\nAverage Final Score:", mean_final_score)

"""How much variation is present in the final scores?"""

final_score_std = students_df["Final_Score"].std()

print("\nStandard Deviation:", final_score_std)

"""Which student obtained the highest final score?"""

best_row = students_df.loc[students_df["Final_Score"].idxmax()]

print("\nStudent with Highest Final Score:")
print(best_row["Student"])
print("Final Score:", best_row["Final_Score"])

"""What relationship do you observe between study hours and final score?"""

hours_score_corr = students_df["Study_Hours"].corr(students_df["Final_Score"])

print("\nCorrelation between Study Hours and Final Score:",
      hours_score_corr)

"""What relationship do you observe between attendance and final score?"""

attendance_score_corr = students_df["Attendance"].corr(students_df["Final_Score"])

print("\nCorrelation between Attendance and Final Score:",
      attendance_score_corr)

"""Which variable has the strongest correlation with final score?"""

final_score_corrs = students_df.corr(numeric_only=True)["Final_Score"]

print("\nCorrelation with Final Score:")
print(final_score_corrs)

"""Why is matrix representation useful for multiple input variables?"""

input_columns = ["Study_Hours", "Attendance", "Assignment_Score"]

input_matrix = students_df[input_columns].values

print("\nMatrix X:")
print(input_matrix)
print("Shape of X:", input_matrix.shape)

"""What does the derivative represent in the study-hours model?"""

def predicted_score(study_hours_input):
    return 40 + 5 * study_hours_input - 0.2 * study_hours_input ** 2


def marginal_gain(study_hours_input):
    return 5 - 0.4 * study_hours_input


for hours in range(1, 11):
    print("Study Hours:", hours,
          "Predicted Score:", predicted_score(hours),
          "Derivative:", marginal_gain(hours))

"""What does the area under the learning-benefit curve represent?"""

def learning_curve(hours):
    return 5 * hours - 0.2 * hours ** 2


hours_points = np.linspace(0, 5, 1000)
curve_values = learning_curve(hours_points)

curve_area = np.trapezoid(curve_values, hours_points)

print("Area under the curve:", curve_area)