# -*- coding: utf-8 -*-
"""WEEK-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qNZ4PgdFPXG8ekXh1-S-gU8TvI8a6Xm

1. Exercise Objective
Analyze an employee dataset using Python, Pandas, NumPy, and Matplotlib. Identify data types and calculate
measures of central tendency, dispersion/spread, and skewness, then visualize and interpret the results.

2. Dataset and Setup
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance",
                   "IT", "HR", "Finance", "IT", "HR"],
    "Age": [22, 25, 28, 30, 24, 35, 40, 27, 29, 45,
            32, 26, 38, 31, 50],
    "Experience": [1, 2, 4, 6, 2, 10, 15, 3, 5, 18,
                   8, 3, 12, 7, 20],
    "Salary": [25000, 28000, 32000, 40000, 27000,
               55000, 80000, 35000, 38000, 95000,
               60000, 30000, 75000, 50000, 150000],
    "Performance_Score": [65, 70, 75, 80, 68,
                          85, 90, 78, 72, 95,
                          88, 74, 92, 82, 96],
    "Training_Completed": ["Yes", "No", "Yes", "Yes", "No",
                           "Yes", "Yes", "No", "Yes", "Yes",
                           "Yes", "No", "Yes", "Yes", "No"]
}

df = pd.DataFrame(data)
print(df)

"""3. Part A – Understanding Data Types

Display the first five records.
"""

print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)

"""Display the data types"""

df.dtypes

"""Classify each variable as categorical or numerical, and identify discrete/continuous variables where appropriate."""

print(df.dtypes)
print(df.select_dtypes(include=np.number).columns.tolist())
print(df.select_dtypes(exclude=np.number).columns.tolist())

"""4. Part B – Basic Data Exploration
Generate descriptive statistics.
"""

df.describe()

"""Find the number of employees in each department."""

print(df["Department"].value_counts())

"""Find the number of employees who completed training."""

print(df["Training_Completed"].value_counts())

"""Check whether there are missing values"""

df.isnull().sum()

"""5. Part C – Measures of Central Tendency
For Age, Experience, Salary, and Performance_Score, calculate mean, median, and mode.

A. Mean
"""

print(df["Age"].mean())
print(df["Experience"].mean())
print(df["Salary"].mean())
print(df["Performance_Score"].mean())

"""B. Median"""

print(df["Age"].median())
print(df["Experience"].median())
print(df["Salary"].median())
print(df["Performance_Score"].median())

"""C. Mode"""

print(df["Age"].mode())
print(df["Experience"].mode())
print(df["Salary"].mode())
print(df["Performance_Score"].mode())

"""6. Part D – Measures of Spread / Dispersion
Calculate the following for Age, Experience, Salary, and Performance_Score.

A. Range
Formula: Range = Maximum − Minimum
"""

print(df["Age"].max() - df["Age"].min())

"""B. Variance"""

print(df["Age"].var())
print(df["Experience"].var())
print(df["Salary"].var())
print(df["Performance_Score"].var())

"""C. Standard Deviation"""

print(df["Age"].std())
print(df["Experience"].std())
print(df["Salary"].std())
print(df["Performance_Score"].std())

"""D. Quartiles and E. IQR"""

Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

"""7. Part E – Skewness"""

print(df[["Age", "Experience", "Salary", "Performance_Score"]].skew())

"""8. Part F – Visualization

A. Histogram
"""

plt.hist(df["Salary"], bins=6)
plt.xlabel("Salary")
plt.ylabel("Frequency")
plt.title("Salary Distribution")
plt.show()

"""B. Box Plot"""

plt.boxplot(df["Salary"])
plt.ylabel("Salary")
plt.title("Salary Box Plot")
plt.show()

"""9. Part G – Combined Statistical Summary"""

summary = pd.DataFrame({
    "Mean": [
        df["Age"].mean(),
        df["Experience"].mean(),
        df["Salary"].mean(),
        df["Performance_Score"].mean()
    ],
    "Median": [
        df["Age"].median(),
        df["Experience"].median(),
        df["Salary"].median(),
        df["Performance_Score"].median()
    ],
    "Std_Deviation": [
        df["Age"].std(),
        df["Experience"].std(),
        df["Salary"].std(),
        df["Performance_Score"].std()
    ],
    "Skewness": [
        df["Age"].skew(),
        df["Experience"].skew(),
        df["Salary"].skew(),
        df["Performance_Score"].skew()
    ]
})
summary.index = ["Age", "Experience", "Salary", "Performance Score"]
print(summary)

"""10. Part H – Data Science Interpretation

 The salary distribution contains a few very high salaries. Is it likely to be positively or negatively skewed?
 Which is likely to be greater for a positively skewed salary distribution: mean or median?
 Remove the employee earning ₹150,000 and calculate the new mean, median, standard deviation, and
skewness. Compare with the original dataset.
 Which measure of central tendency would be more representative of salary when extreme salaries exist?
Explain using your results.
 Which measure of spread would you prefer when extreme values are present: range, standard deviation, or
IQR? Explain.
"""

df2 = df[df["Salary"] != 150000]

print(df2["Salary"].mean())
print(df2["Salary"].median())
print(df2["Salary"].std())
print(df2["Salary"].skew())

Q1 = df2["Salary"].quantile(0.25)
Q3 = df2["Salary"].quantile(0.75)
print(Q3 - Q1)
print(df2["Salary"].max() - df2["Salary"].min())

"""11. Part I – Group-Based Analysis"""

print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].median())
print(df.groupby("Department")["Salary"].std())

"""Compare departments based on mean salary, median salary, and salary variation. Explain what the statistics show
rather than simply ranking departments.
"""

print(df.groupby("Department")["Salary"].agg(["mean", "median", "std"]))
print(df.groupby("Department")["Salary"].std() / df.groupby("Department")["Salary"].mean() * 100)

"""12. Part J – Final Challenge
Write a Python program that automatically calculates the following for all numerical columns:
Mean, Median, Mode, Minimum, Maximum, Range, Variance, Standard Deviation, Q1, Q3, IQR, and Skewness.
"""

numeric_columns = df.select_dtypes(include=np.number).columns

for column in numeric_columns:
    print("\n", column)
    print("Mean:", df[column].mean())
    print("Median:", df[column].median())
    print("Mode:", df[column].mode().tolist())
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())
    print("Range:", df[column].max() - df[column].min())
    print("Variance:", df[column].var())
    print("Standard Deviation:", df[column].std())
    print("Q1:", df[column].quantile(0.25))
    print("Q3:", df[column].quantile(0.75))
    print("IQR:", df[column].quantile(0.75) - df[column].quantile(0.25))
    print("Skewness:", df[column].skew())