# -*- coding: utf-8 -*-
"""WEEK-8 PROBABILITY STATISTICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KM-VfabDlOus_ubJa5lcT4wUFrlh3yda
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style='whitegrid')
np.random.seed(42)
df = sns.load_dataset('tips')
print('Loaded tips dataset:', df.shape)
df.head()

"""1. Types of data & variables"""

# -----------------------------------------------------------
# 🔹 1A. NUMERICAL vs CATEGORICAL COLUMNS
# -----------------------------------------------------------

# .dtypes tells you each column's type: float/int = numerical, object/category = categorical
print(df.dtypes)

numerical   = df.select_dtypes(include='number').columns.tolist()
categorical = df.select_dtypes(exclude='number').columns.tolist()
print('\nNumerical  :', numerical)
print('Categorical:', categorical)

# -----------------------------------------------------------
# 🔹 1B. WHICH STATISTIC FITS WHICH TYPE
# -----------------------------------------------------------

# Numerical -> mean / std make sense
print('Mean total_bill:', round(df['total_bill'].mean(), 2))

# Categorical -> counts / mode make sense (mean would be meaningless)
print('Day value counts:')
print(df['day'].value_counts())

""" LAB EXERCISE 1 — Classify the columns
Print the list of numerical columns and the list of categorical columns.
For a numerical column (e.g. tip), print its mean.
For a categorical column (e.g. sex), print its value counts.
"""

# 1. Numerical vs categorical columns
numerical = df.select_dtypes(include="number").columns.tolist()
categorical = df.select_dtypes(exclude="number").columns.tolist()
print("Numerical  :", numerical)
print("Categorical:", categorical)

# 2. Mean of a numerical column (tip)
print("Mean tip:", round(df["tip"].mean(), 2))

# 3. Value counts of a categorical column (sex)
print(df["sex"].value_counts())

"""2. Measures of central tendency"""

# -----------------------------------------------------------
# 🔹 2A. MEAN, MEDIAN, MODE
# -----------------------------------------------------------

col = df['total_bill']
print('Mean   :', round(col.mean(), 2))    # average; sensitive to outliers
print('Median :', round(col.median(), 2))  # middle value; robust to outliers
print('Mode   :', round(col.mode()[0], 2)) # most frequent value

# -----------------------------------------------------------
# 🔹 2B. WHEN MEAN AND MEDIAN DISAGREE (skew)
# -----------------------------------------------------------

# A right-skewed column drags the mean above the median
print('mean > median ?', col.mean() > col.median(), '-> right-skewed')

plt.figure(figsize=(7, 3.5))
sns.histplot(col, kde=True)
plt.axvline(col.mean(),   color='red',   label='mean')
plt.axvline(col.median(), color='green', label='median')
plt.legend(); plt.title('total_bill: mean vs median'); plt.show()

"""🧪 LAB EXERCISE 2 — Central tendency
For the tip column:

Print its mean, median and mode.
Is it right-skewed? Check whether mean > median.
Plot a histogram of tip with vertical lines at the mean and median.
"""

tip = df['tip']

# 1. mean, median, mode
print('Mean   :', round(tip.mean(), 2))
print('Median :', round(tip.median(), 2))
print('Mode   :', round(tip.mode()[0], 2))

# 2. mean > median ?
print('mean > median ?', tip.mean() > tip.median(), '-> right-skewed')

# 3. histogram with mean & median lines (reuse the pattern from 2B)
plt.figure(figsize=(7, 3.5))
sns.histplot(tip, kde=True)
plt.axvline(tip.mean(),   color='red',   label='mean')
plt.axvline(tip.median(), color='green', label='median')
plt.legend(); plt.title('tip: mean vs median'); plt.show()

"""3. Measures of spread (dispersion)"""

# -----------------------------------------------------------
# 🔹 3A. RANGE, VARIANCE, STANDARD DEVIATION
# -----------------------------------------------------------

col = df['total_bill']
print('Range :', round(col.max() - col.min(), 2))   # max - min
print('Var   :', round(col.var(), 2))                # variance (sigma^2)
print('Std   :', round(col.std(), 2))                # std deviation (sigma)

# -----------------------------------------------------------
# 🔹 3B. QUARTILES & THE INTERQUARTILE RANGE (IQR)
# -----------------------------------------------------------

q1, q3 = col.quantile(0.25), col.quantile(0.75)
iqr = q3 - q1
print('Q1 (25%):', round(q1, 2))
print('Q3 (75%):', round(q3, 2))
print('IQR     :', round(iqr, 2), '-> spread of the middle 50% (robust to outliers)')

"""🧪 LAB EXERCISE 3 — Spread
For the tip column:

Print the range, variance and standard deviation.
Compute Q1, Q3 and the IQR.
In a comment, say which measure of spread is most robust to outliers and why.
"""

tip = df['tip']

# 1. range, variance, std
print('Range :', round(tip.max() - tip.min(), 2))
print('Var   :', round(tip.var(), 2))
print('Std   :', round(tip.std(), 2))

# 2. Q1, Q3, IQR
q1, q3 = tip.quantile(0.25), tip.quantile(0.75)
iqr = q3 - q1
print('Q1 (25%):', round(q1, 2))
print('Q3 (75%):', round(q3, 2))
print('IQR     :', round(iqr, 2))

"""4. Shape: five-number summary & box plot"""

# -----------------------------------------------------------
# 🔹 4A. FIVE-NUMBER SUMMARY (min, Q1, median, Q3, max)
# -----------------------------------------------------------

col = df['total_bill']
five = col.describe()[['min', '25%', '50%', '75%', 'max']]
print(five)

# Skewness: > 0 means a right tail, < 0 a left tail, ~0 symmetric
print('\nSkewness:', round(col.skew(), 3))

# -----------------------------------------------------------
# 🔹 4B. BOX PLOT (a picture of the five-number summary)
# -----------------------------------------------------------

# The box spans Q1..Q3 (the IQR), the line is the median,
# whiskers reach the rest, and dots beyond them are outliers.
plt.figure(figsize=(7, 2.8))
sns.boxplot(x=df['total_bill'])
plt.title('Box plot of total_bill'); plt.show()

"""🧪 LAB EXERCISE 4 — Five-number summary & box plot
For the tip column:

Print its five-number summary (min, 25%, 50%, 75%, max).
Print its skewness and say (in a comment) which way it leans.
Draw a box plot of tip.
"""

tip = df['tip']

# 1. five-number summary
five = tip.describe()[['min', '25%', '50%', '75%', 'max']]
print(five)

# 2. skewness (+ comment on the direction of the lean)
print('\nSkewness:', round(tip.skew(), 3))
# Skewness is about 1.47 (> 0), so tip leans right: most tips are small
# and a few large tips form a long right tail.

# 3. box plot of tip
plt.figure(figsize=(7, 2.8))
sns.boxplot(x=tip)
plt.title('Box plot of tip'); plt.show()

"""#5. Correlation & summarizing a dataset"""

# -----------------------------------------------------------
# 🔹 5A. CORRELATION between numerical columns
# -----------------------------------------------------------

# .corr() returns a matrix of correlations in the range -1 .. +1
corr = df.corr(numeric_only=True)
print(corr.round(2))

# correlation is NOT causation, and it only measures LINEAR relationships
print('\ntotal_bill vs tip:', round(corr.loc['total_bill', 'tip'], 2), '-> strong positive')

# -----------------------------------------------------------
# 🔹 5B. VISUALISE THE CORRELATION MATRIX
# -----------------------------------------------------------

plt.figure(figsize=(5, 4))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='Blues', vmin=-1, vmax=1)
plt.title('Correlation matrix'); plt.show()

# -----------------------------------------------------------
# 🔹 5C. ONE-SHOT SUMMARY with .describe()
# -----------------------------------------------------------

# describe() returns count, mean, std, min, quartiles and max for every numeric column
df.describe()

"""#### 🧪 LAB EXERCISE 5 — Correlation & full summary

1. Build the correlation matrix and print it (rounded to 2 decimals).
2. Draw a correlation **heatmap**.
3. Run `df.describe()` and, in a comment, write **3 insights** about the dataset (e.g. which column is most spread out, which pair is most correlated, any skew you notice).
"""

# 1. correlation matrix (rounded)
corr = df.corr(numeric_only=True)
print(corr.round(2))

# 2. heatmap of the correlation matrix
plt.figure(figsize=(5, 4))
sns.heatmap(corr, annot=True, cmap='Blues', vmin=-1, vmax=1)
plt.title('Correlation matrix'); plt.show()

# 3. df.describe() + 3 insights as comments
print(df.describe())
# Insight 1: total_bill is the most spread out column (std about 8.9, range
#            about 47.7), compared with tip (std about 1.4) and size (std about 1.0).
#            Note that std depends on the scale of each column, so this is a
#            comparison of raw spread, not relative spread.
# Insight 2: total_bill and tip are the most correlated pair (r about 0.68):
#            bigger bills come with bigger tips. Correlation is not causation,
#            and it only measures linear relationships.
# Insight 3: total_bill and tip are right-skewed (mean > median, and the max
#            values of 50.81 and 10 are far above the 75th percentile). Most
#            parties are small (median size = 2).